export const TRANSACTION_STATUS = Object.freeze({
  PENDING: "pending",
  FUNDED: "funded",
  INPROGRESS: "inprogress",
  INSPECTION: "inspection",
  AUDIT: "audit",
  APPROVED: "approved",
  COMPLETED: "completed",
  DISPUTED: "disputed",
  REVISION: "revision",
});

export const ACTIVE_TRANSACTION_STATUSES = [
  TRANSACTION_STATUS.PENDING,
  TRANSACTION_STATUS.FUNDED,
  TRANSACTION_STATUS.INPROGRESS,
  TRANSACTION_STATUS.INSPECTION,
  TRANSACTION_STATUS.AUDIT,
  TRANSACTION_STATUS.APPROVED,
  TRANSACTION_STATUS.REVISION,
];

export const CLOSED_TRANSACTION_STATUSES = [TRANSACTION_STATUS.COMPLETED];
