import { TRANSACTION_ACTION } from "./transactionActions.js";
import { TRANSACTION_STATUS } from "./transactionStatus.js";

export const ACTION_STATUS_MAP = Object.freeze({
  [TRANSACTION_ACTION.FUND_ESCROW]: TRANSACTION_STATUS.FUNDED,

  [TRANSACTION_ACTION.START_WORK]: TRANSACTION_STATUS.INPROGRESS,

  [TRANSACTION_ACTION.SUBMIT_WORK]: TRANSACTION_STATUS.INSPECTION,

  [TRANSACTION_ACTION.REQUEST_REVISION]: TRANSACTION_STATUS.REVISION,

  [TRANSACTION_ACTION.APPROVE_WORK]: TRANSACTION_STATUS.APPROVED,

  [TRANSACTION_ACTION.OPEN_DISPUTE]: TRANSACTION_STATUS.DISPUTED,

  [TRANSACTION_ACTION.COMPLETE]: TRANSACTION_STATUS.COMPLETED,
});

export function getNextStatus(action) {
  return ACTION_STATUS_MAP[action] || null;
}
